const DATA = window.SALES_DATA || [];
const $ = id => document.getElementById(id);
const nf = new Intl.NumberFormat("en-US",{maximumFractionDigits:0});
const money = v => ((v||0)/1e6).toFixed(2)+" MB";
const pct = v => ((v||0)*100).toFixed(1)+"%";
const num = v => nf.format(Math.round(v||0));
const esc = s => String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const PRODUCT_DEEP_LINKS={"DEVICE":"product_deep_dive.html","GIA":"product_deep_dive.html","POSTPAID":"postpay_deep_dive.html","TRUE ONLINE":"tol_deep_dive.html","PREPAID":"prepaid_deep_dive.html","TRUE VISION":"tvs_deep_dive.html"};
const productLink=p=>PRODUCT_DEEP_LINKS[String(p).trim()]||"bma1.html";
const filters={fYear:r=>r.YEAR,fMonth:r=>r.MONTH,fChannel:r=>r.CHANNEL,fProduct:r=>r.PRODUCT,fShop:r=>r.SHOP_NAME};
function uniq(a){return [...new Set(a.filter(x=>x!==""&&x!==null&&x!==undefined))]}
function setOptions(id,vals,label){const el=$(id),cur=el.value;el.innerHTML=`<option value="">${label}</option>`+uniq(vals).sort((a,b)=>String(a).localeCompare(String(b),undefined,{numeric:true})).map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join("");if([...el.options].some(o=>o.value===cur))el.value=cur;}
function scopedBase(){return DATA.filter(r=>String(r.AREA)==="BMA I (North West)")}
function activeRows(){return scopedBase().filter(r=>Object.keys(filters).every(id=>{const v=$(id).value;return !v||String(filters[id](r))===v;}));}
function aggregate(rows){return rows.reduce((a,r)=>{a.tq+=+r.TARGET_BOTTOMUP_QTY||0;a.ta+=+r.TARGET_BOTTOMUP_NET_AMOUNT||0;a.q+=+r.QTY||0;a.a+=+r.NET_AMOUNT||0;return a;},{tq:0,ta:0,q:0,a:0});}
function status(x){return x>=1?"ACHIEVE":x>=.95?"WATCH":x>=.8?"RISK":"CRITICAL"}
function cls(x){return x>=1?"good":x>=.95?"watch":x>=.8?"risk":"critical"}
function setInitialFromUrl(){
  const q=new URLSearchParams(location.search);
  const vals={fYear:q.get("year")||"2026",fMonth:q.get("month")||"8",fChannel:q.get("channel")||"",fProduct:q.get("product")||"",fShop:q.get("shop")||""};
  Object.entries(vals).forEach(([id,v])=>{if($(id)&&[...$(id).options].some(o=>o.value===v))$(id).value=v;});
}
function refreshDependent(){
  const selected={};Object.keys(filters).forEach(id=>selected[id]=$(id).value);let rows=scopedBase();
  if(selected.fYear)rows=rows.filter(r=>String(r.YEAR)===selected.fYear);setOptions("fMonth",rows.map(r=>r.MONTH),"All Months");
  rows=scopedBase();if(selected.fYear)rows=rows.filter(r=>String(r.YEAR)===selected.fYear);if(selected.fMonth)rows=rows.filter(r=>String(r.MONTH)===selected.fMonth);setOptions("fChannel",rows.map(r=>r.CHANNEL),"All Channels");
  rows=scopedBase();if(selected.fYear)rows=rows.filter(r=>String(r.YEAR)===selected.fYear);if(selected.fMonth)rows=rows.filter(r=>String(r.MONTH)===selected.fMonth);if(selected.fChannel)rows=rows.filter(r=>String(r.CHANNEL)===selected.fChannel);setOptions("fProduct",rows.map(r=>r.PRODUCT),"All Products");
  rows=scopedBase();if(selected.fYear)rows=rows.filter(r=>String(r.YEAR)===selected.fYear);if(selected.fMonth)rows=rows.filter(r=>String(r.MONTH)===selected.fMonth);if(selected.fChannel)rows=rows.filter(r=>String(r.CHANNEL)===selected.fChannel);if(selected.fProduct)rows=rows.filter(r=>String(r.PRODUCT)===selected.fProduct);setOptions("fShop",rows.map(r=>r.SHOP_NAME),"All Shops");
  Object.keys(filters).forEach(id=>{if([...$(id).options].some(o=>o.value===selected[id]))$(id).value=selected[id];});
}
function populate(){const b=scopedBase();setOptions("fYear",b.map(r=>r.YEAR),"All Years");setOptions("fMonth",b.map(r=>r.MONTH),"All Months");setOptions("fChannel",b.map(r=>r.CHANNEL),"All Channels");setOptions("fProduct",b.map(r=>r.PRODUCT),"All Products");setOptions("fShop",b.map(r=>r.SHOP_NAME),"All Shops");setInitialFromUrl();refreshDependent();setInitialFromUrl();}
function updateKPIs(rows){const x=aggregate(rows),aa=x.ta?x.a/x.ta:0,qa=x.tq?x.q/x.tq:0,asp=x.q?x.a/x.q:0;$("kAmount").textContent=money(x.a);$("kAmountTarget").textContent=money(x.ta);$("kAmountAch").textContent=pct(aa);$("kAmountGap").textContent=(x.a-x.ta>=0?"+":"")+money(x.a-x.ta);$("kQty").textContent=num(x.q);$("kQtyTarget").textContent=num(x.tq);$("kQtyAch").textContent=pct(qa);$("kQtyGap").textContent=(x.q-x.tq>=0?"+":"")+num(x.q-x.tq);$("kAsp").textContent=x.q?nf.format(asp):"-";$("kStatus").textContent=status(aa);$("kStatus").className=cls(aa);$("kStatusNote").textContent=aa>=1?"Amount target achieved":`Gap ${pct(Math.abs(1-aa))} to target`;const scope=[`BMA I (North West)`];if($("fYear").value)scope.push(`Year: ${$("fYear").value}`);if($("fMonth").value)scope.push(`Month: ${$("fMonth").value}`);if($("fChannel").value)scope.push(`Channel: ${$("fChannel").value}`);if($("fProduct").value)scope.push(`Product: ${$("fProduct").value}`);if($("fShop").value)scope.push(`Shop: ${$("fShop").value}`);$("subtitle").textContent=scope.join(" • ")+" • Net Amount + QTY Performance";$("insightText").textContent=aa<1?`Net Amount is ${pct(aa)} of target, with a gap of ${money(Math.abs(x.a-x.ta))}. ${qa<1?`QTY is ${pct(qa)} of target, with a gap of ${num(Math.abs(x.q-x.tq))}.`:"QTY is at target."}`:`Net Amount achieved ${pct(aa)} of target. ${qa<1?`QTY is ${pct(qa)} of target.`:"QTY is at target."}`;$("keyMessage").textContent=`BMA I status: ${status(aa)} (${pct(aa)}). QTY status: ${status(qa)} (${pct(qa)}).`;$("actionMessage").textContent=qa<aa?"Focus on volume recovery while protecting ASP; prioritize products and shops with the largest gaps.":"Focus on sustaining volume while improving value per unit and mix.";}
function monthly(rows){const by={};rows.forEach(r=>{const k=`${r.YEAR}-${String(r.MONTH).padStart(2,"0")}`;(by[k]??={a:0,t:0,q:0,tq:0}).a+=+r.NET_AMOUNT||0;by[k].t+=+r.TARGET_BOTTOMUP_NET_AMOUNT||0;by[k].q+=+r.QTY||0;by[k].tq+=+r.TARGET_BOTTOMUP_QTY||0});return Object.entries(by).sort().map(([k,v])=>({...v,k:k.slice(5)}));}
function renderTrend(){let rows=scopedBase().filter(r=>Object.keys(filters).every(id=>id!=="fMonth"&&(!$(id).value||String(filters[id](r))===$(id).value)));const d=monthly(rows);const max=Math.max(...d.map(x=>x.a),...d.map(x=>x.t),1),maxq=Math.max(...d.map(x=>x.q),...d.map(x=>x.tq),1);$("trendChart").innerHTML=`<div class="bars">${d.map(x=>`<div class="chartcol"><div class="barwrap"><div class="bar actual" style="height:${x.a/max*100}%"></div><div class="bar target" style="height:${x.t/max*100}%"></div></div><div class="barlabel">${x.k}</div></div>`).join("")}</div><div class="legend">Actual ■ &nbsp; Target ■ • Selected month: ${$("fMonth").value||"All"}</div>`;$("volumeChart").innerHTML=`<div class="bars">${d.map(x=>`<div class="chartcol"><div class="barwrap"><div class="bar qty" style="height:${x.q/maxq*100}%"></div><div class="bar target" style="height:${x.tq/maxq*100}%"></div></div><div class="barlabel">${x.k}</div></div>`).join("")}</div><div class="legend">Actual QTY ■ &nbsp; Target QTY ■ • Selected month: ${$("fMonth").value||"All"}</div>`;}
function renderProduct(rows){const by={};rows.forEach(r=>{const k=r.PRODUCT;(by[k]??={a:0,t:0,q:0,tq:0}).a+=+r.NET_AMOUNT||0;by[k].t+=+r.TARGET_BOTTOMUP_NET_AMOUNT||0;by[k].q+=+r.QTY||0;by[k].tq+=+r.TARGET_BOTTOMUP_QTY||0});const arr=Object.entries(by).map(([k,v])=>({k,...v,aa:v.t?v.a/v.t:0,qa:v.tq?v.q/v.tq:0,asp:v.q?v.a/v.q:0})).sort((a,b)=>b.a-a.a);$("productTable").innerHTML=`<div class="tablewrap"><table class="data-table"><thead><tr><th>Product</th><th>Net Amount</th><th>Amt Ach.</th><th>QTY</th><th>QTY Ach.</th><th>ASP</th></tr></thead><tbody>${arr.map(x=>`<tr><td><a href="${productLink(x.k)}" class="product-link">${esc(x.k)}</a></td><td>${money(x.a)}</td><td class="${cls(x.aa)}">${pct(x.aa)}</td><td>${num(x.q)}</td><td class="${cls(x.qa)}">${pct(x.qa)}</td><td>${nf.format(x.asp)}</td></tr>`).join("")}</tbody></table></div>`;}
function renderShops(rows){const by={};rows.forEach(r=>{const k=r.SHOP_NAME;(by[k]??={a:0,t:0,q:0,tq:0}).a+=+r.NET_AMOUNT||0;by[k].t+=+r.TARGET_BOTTOMUP_NET_AMOUNT||0;by[k].q+=+r.QTY||0;by[k].tq+=+r.TARGET_BOTTOMUP_QTY||0});const arr=Object.entries(by).map(([k,v])=>({k,...v,aa:v.t?v.a/v.t:0,qa:v.tq?v.q/v.tq:0,asp:v.q?v.a/v.q:0})).filter(x=>x.a||x.t).sort((a,b)=>(b.a-b.t)-(a.a-a.t));const show=[...arr.slice(0,10),...arr.slice(-10)].filter((x,i,a)=>a.findIndex(y=>y.k===x.k)===i);$("shopTable").innerHTML=`<div class="tablewrap"><table class="data-table"><thead><tr><th>Shop</th><th>Net Amount</th><th>Amt Ach.</th><th>Gap</th><th>QTY</th><th>QTY Ach.</th><th>ASP</th></tr></thead><tbody>${show.map(x=>`<tr><td>${esc(x.k)}</td><td>${money(x.a)}</td><td class="${cls(x.aa)}">${pct(x.aa)}</td><td class="${x.a-x.t>=0?'good':'critical'}">${(x.a-x.t>=0?"+":"")}${money(x.a-x.t)}</td><td>${num(x.q)}</td><td class="${cls(x.qa)}">${pct(x.qa)}</td><td>${nf.format(x.asp)}</td></tr>`).join("")}</tbody></table></div>`;}
function render(){refreshDependent();const rows=activeRows();updateKPIs(rows);renderTrend();renderProduct(rows);renderShops(rows);}
Object.keys(filters).forEach(id=>$(id).addEventListener("change",render));
$("resetBtn").addEventListener("click",()=>{Object.keys(filters).forEach(id=>$(id).value="");$("fYear").value="2026";$("fMonth").value="8";render();});
populate();render();
